"""
WebSocket Event Logger
Structured logging for connection, messages, and responses
"""
import logging
from datetime import datetime
from typing import Literal, Optional

logger = logging.getLogger(__name__)


class WebSocketLogger:
    """Structured logging for WebSocket events"""
    
    @staticmethod
    def log_user_connected(username: str, is_authenticated: bool):
        """
        Log user connection
        Format: User connected: "username" || "guest user"
        """
        user_type = f'"{username}"' if is_authenticated else '"guest user"'
        logger.info(f"✅ User connected: {user_type}")
    
    @staticmethod
    def log_user_disconnected(username: str, is_authenticated: bool):
        """
        Log user disconnection
        Format: User disconnected: "username" || "guest user"
        """
        user_type = f'"{username}"' if is_authenticated else '"guest user"'
        logger.info(f"❌ User disconnected: {user_type}")
    
    @staticmethod
    def log_user_query(username: str, message: str, is_authenticated: bool):
        """
        Log user query/message
        Format: User query: "message"
        """
        user_type = "authenticated" if is_authenticated else "guest"
        logger.info(f"📨 User query ({user_type}): {username} - {message[:100]}")
    
    @staticmethod
    def log_response_generated(
        provider: Literal["grok", "gemini", "fallback"],
        response_text: str,
        is_authenticated: bool,
        username: str
    ):
        """
        Log response generation
        Format: Response generated by {provider}, response: {response_text}
        """
        user_type = "authenticated" if is_authenticated else "guest"
        logger.info(
            f"📤 Response by {provider} ({user_type}): {username} - {response_text[:100]}"
        )
    
    @staticmethod
    def log_fallback_triggered(reason: str, username: str):
        """
        Log fallback response triggered
        """
        logger.warning(f"⚠️ Fallback triggered for {username}: {reason}")
